Validations and model specs
shm04/blogApp pull request #3
Opened 2023-10-26 19:07 UTC by shm04

## Validations and model specs

### In this pull request I add the following changes:

- Add the following validations:
   - For the User model:
       - Name must not be blank.
       - PostsCounter must be an integer greater than or equal to zero.
   - For the Post model:
      - Title must not be blank.
      - Title must not exceed 250 characters.
      - CommentsCounter must be an integer greater than or equal to zero.
       - LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

2023-10-26 20:13 UTC, cynthiainga requested changes
Hi @shm04, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] All implemented tests are passing ✔️ 
- [ ] Correct Gitflow ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 20:13 UTC, cynthiainga commented on spec/models/user_spec.rb
- [ ] Good job so far but as mentioned in the project requirement all of your models' methods should be tested, kindly add the test for `recent_posts` method 🙃

2023-10-26 20:13 UTC, cynthiainga commented on spec/models/post_spec.rb
- [ ] Good job so far but as mentioned in the project requirement all of your models' methods should be tested, kindly add the test for `recent_comments` and `update_user_posts_counter` methods 🙃 🙃

2023-10-26 20:13 UTC, cynthiainga commented on spec/models/like_spec.rb
- [ ] Good job so far but as mentioned in the project requirement all of your models' methods should be tested, kindly add the test for the `update_post_likes_counter` method 😁

2023-10-26 20:13 UTC, cynthiainga commented on spec/models/comment_spec.rb
- [ ] Good job so far but as mentioned in the project requirement all of your models' methods should be tested, kindly add the test for the `update_post_comments_counter` method 😁

2023-10-28 18:35 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @shm04    :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 18:35 UTC, merged