Blog app - integration specs for views and fix n+1 problems
shm04/blogApp pull request #8
Opened 2023-11-08 20:07 UTC by shm04

## Integration specs for views and fix n+1 problems

### In this pull request we made the following changes:

   - Make sure that the N+1 problem is solved when fetching all posts and their comments for a user

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.
 
- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

2023-11-09 21:14 UTC, OyePriscilla requested changes
Hi @shm04 👏 👏 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Write integration tests with Capybara gem. ✔️ 
Secure app from n+1 problems. ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 21:14 UTC, OyePriscilla commented on spec/features/user_index_spec.rb
> +  end
- [ ] Please kindly add test that assert that profile picture is present as stated in the requirement. ℹ️ 

<img width="409" alt="Untitled" src="https://github.com/shm04/blogApp/assets/103386183/00eec74a-2072-4661-a205-40b0d826d49b">

2023-11-09 21:14 UTC, OyePriscilla commented on spec/features/user_show_spec.rb
> +  end
- [ ] Please kindly add the missing tests as highlighted in the screenshot below. 👇 
 
<img width="453" alt="Untitled" src="https://github.com/shm04/blogApp/assets/103386183/1101911a-d773-49ce-8b30-633ac2503445">

2023-11-09 21:14 UTC, OyePriscilla commented on spec/features/post_index_spec.rb
> +  end
- [ ] Please kindly add the missing test for the post_index page as highlighted in the screenshot in accordance to the requirement. 🙏 

<img width="498" alt="Untitled" src="https://github.com/shm04/blogApp/assets/103386183/9db6ce0f-933c-40ca-b4ff-045dedf360b1">

2023-11-09 21:14 UTC, OyePriscilla commented on spec/features/post_show_spec.rb
> +    expect(page).to have_content("Likes: #{post.likes_counter}")
- [ ] This test 👇 is not yet added to your implementation, kindly attend to it.  👍 

<img width="291" alt="Untitled" src="https://github.com/shm04/blogApp/assets/103386183/8e4229f5-2428-4c29-b767-5277fdafbe0d">

2023-11-10 20:05 UTC, cynthiainga requested changes
Hi @shm04, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights

- [ ] All implemented tests are passing ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 20:05 UTC, cynthiainga commented on spec/features/user_show_spec.rb
> +    expect(page).to have_content("Number of posts: #{user.posts.size}")
- [ ] As mentioned by the previous reviewer you should add a test that we can see the user's profile picture 🙃 
- [ ] Also a test that we can see the user's first 3 posts, which means you should test the recent_posts method 🙃 🙃

2023-11-10 20:05 UTC, cynthiainga commented on spec/features/post_index_spec.rb
- [ ] As mentioned by the previous reviewer you should add a test for pagination, we can see a section for pagination if there are more posts than fit on the view 🙃 🙃

2023-11-10 22:12 UTC, cynthiainga approved these changes
Hi @shm04, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] All changes are made ✔️ 
- [ ] All tests are passing ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 22:42 UTC, merged